# clusters/k3s-server/serviceaccounts.yaml
# Creates all service accounts needed on k3s-server:
#   - vault-auth (n: kube-system)           -> token reviewer for Vault
#   - external-secrets (n: external-secrets) -> used by ESO to read from Vault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
