# clusters/rancher-master/serviceaccounts.yaml
# Creates all service accounts needed on rancher-master:
#   - vault-auth (n: vault)         -> token reviewer for Vault
#   - cert-manager (n: cert-manager) -> used by cert-manager pods
#   - cert-pusher (n: cert-manager)  -> used by PushSecret to write to Vault
#   - external-secrets (n: external-secrets) -> used by ESO to read from Vault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: vault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-pusher
  namespace: cert-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
